name: Package Analyzer

on: [push, pull_request, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # required
    - uses: axel-op/dart-package-analyzer@v3
      with:
        # Required:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
